### ISSUE TITLE
Function getArrayTitles in okhubwrapper.response.inc needs updating

### ISSUE THREAD

**Issue by pmasonids** [oriel-hub/OKHub-HTML-Widget#1]
The method/function getArrayTitles should call method $object->getField instead of direct reference to property - e.g. $object->title should be $object->getTitle('title')

**Comment by joe-mcpherson** [comment]
Ahh ok I think I see what you mean now (I don't think the Drupal module was referencing this functionality  from okhubwrapper.responce.inc so I didn't need to modify it) 
I think $object->title should actually be $object->get_value('title'). I'll work with you on it when in the office tomorrow.

**Comment by joe-mcpherson** [comment]
I've update the getArrayTitles() function in the latest commit. Please test this against your usecase

**Comment by joe-mcpherson** [comment]
Fixed for widget in wrapper
