### ISSUE TITLE
Customised widget loses filters on search

### ISSUE THREAD

**Issue by pmasonids** [oriel-hub/OKHub-HTML-Widget#19]
A customised widget is implemented on a website. If a visitor then makes a text search, the filters are lost and results come from the whole of the OKhub.
There is no way to return to the filtered list (or remove the search as searching for nothing returns no results)

The customised widget should retain all filters once implemented on a site.

**Comment by joe-mcpherson** [comment]
That's now fixed. When using the search box now the widget will maintain the configured Themes, Countries, Regions etc...
